#!/bin/bash

# Regenerating SSH Key
/bin/rm -f /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server

# Setting linuxadmin password
echo "Please change the password for the user linuxmadmin"
read -p "Press Enter to continue." -n 1 -r
echo
passwd linuxadmin

# Dist Upgrade
echo "Now it is strongly advised to update your system, before"
echo "you join your domain an create a new image."
echo
read -p "Make a dist-upgrade [y/n] ?"
echo   
if [[ $REPLY =~ ^[YyJj]$ ]]
then
    apt-get update
    apt-get dist-upgrade
fi

# Do more stuff
linuxmuster-client-adsso-setup



