#!/bin/bash

# Regenerating SSH Key
/bin/rm -f /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server

# Setting linuxadmin password
if [ -e "/.linbo" ]; then
    echo "Ich vermute, dass das generische Postsyncskript verwendet wurde "
    echo "und für linuxadmin ein Passwort gesetzt wurde. "
    echo "Das Setzen des Passwortes für den Benutzer kann daher übersprungen werden."
fi
read -p "Möchtest du ein neues Passwort für linuxadmin vergeben? [j/N] "
read -p "Bitte vergib ein neues Passwort für den Benutzer linuxadmin." -n 1 -r
echo
if [[ $REPLY =~ ^[YyJj]$ ]]
then
    passwd linuxadmin
fi

# Dist Upgrade
echo "Wir empfehlen dringend, jetzt das System zu updaten, dann"
echo "der Domäne beizutreten und danach ein neues Image zu erstellen."
echo
read -p "Upgrade durchführen [j/N] ?"
echo   
if [[ $REPLY =~ ^[YyJj]$ ]]
then
    apt-get update
    apt-get dist-upgrade
fi

# Do more stuff
linuxmuster-client-adsso-setup



